### PR TITLE
file an application to join the members: coldnight

### PR DESCRIPTION
**Pull request by coldnight**

### CODE REVIEW

**Review by nkysg — APPROVED** [review]

**Comment by coldnight** [comment]
What an honor, thanks @nkysg , and many thanks to @jolestar .

**Comment by jolestar** [comment]
```
curl 'http://main.seed.starcoin.org/' \
  -H 'content-type: application/json' \
  --data-raw '{"jsonrpc":"2.0","method":"contract.call_v2","params":[{"function_id":"0x00000000000000000000000000000001::PriceOracle::read","args":["0x82e35b34096f32c42061717c06e44a59"],"type_args":["0x00000000000000000000000000000001::STCUSDOracle::STCUSD"]}],"id":0}'
{"jsonrpc":"2.0","result":[56000],"id":0}
```
1000USD/0.056000 = 17858

https://stcscan.io/main/transactions/detail/0x00961b32769956daf517849f8312dde3b4f2d3d3d35cc88961c3543143db752d

**Comment by jolestar** [comment]
@coldnight 的 一个 Move PR 没有写到学习成果中 https://github.com/starcoinorg/starcoin-framework-commons/pull/37 这里补充一下。

**Comment by jolestar** [comment]
to @nkysg 1785.8 STC

https://stcscan.io/main/transactions/detail/0xea00e773e6426f58ab200e6dd428dcb73b5a385b982ad093a6cb80aea16a4701

**Pull request merged**
