### PR TITLE
add member jerrykwan

### PR DESCRIPTION
**Pull request by JerryKwan**
add member jerrykwan

### CODE REVIEW

**Comment by nkysg** [comment]
@JerryKwan congratulations。Looking forward to make more contribution.

**Review by nkysg — APPROVED** [review]

**Comment by jolestar** [comment]
@JerryKwan Need more practice about Move.

**Comment by JerryKwan** [comment]
@jolestar Yes, will invest more time on Move later

**Comment by nkysg** [comment]
https://github.com/starcoinorg/web3startrek/pull/58 add more pull request links @jolestar

**Comment by jolestar** [comment]
```
curl 'http://main.seed.starcoin.org/' \
  -H 'content-type: application/json' \
  --data-raw '{"jsonrpc":"2.0","method":"contract.call_v2","params":[{"function_id":"0x00000000000000000000000000000001::PriceOracle::read","args":["0x82e35b34096f32c42061717c06e44a59"],"type_args":["0x00000000000000000000000000000001::STCUSDOracle::STCUSD"]}],"id":0}'
{"jsonrpc":"2.0","result":[36105],"id":0}
```

1000USD/0.036105 = 27697 STC

**Comment by jolestar** [comment]
https://stcscan.io/main/transactions/detail/0xe4d1fe4fa7a7239bc7e13d38f1a76f646753bec181919d8a3f62b55abda8e856

**Comment by jolestar** [comment]
to @nkysg 2769.7 STC

https://stcscan.io/main/transactions/detail/0xa21c72f934137ed0c13aa0c6df162cf0f31f6d1a0234b02c3c811b3d2af36dc1

**Pull request merged**
