### PR TITLE
application from jiangying

### PR DESCRIPTION
**Pull request by djy0**

### CODE REVIEW

**Comment by djy0** [comment]
@jolestar Hi, I am applying for graduate

**Review by jolestar — APPROVED** [review]

**Comment by djy0** [comment]
The address in original pr file is from gate.io.
For distributing nft, please use the address from starmask:
0x2b547120e3C36DEAC1d6c93dca8C4D40

**Comment by jolestar** [comment]
> The address in original pr file is from gate.io. For distributing nft, please use the address from starmask: 0x2b547120e3C36DEAC1d6c93dca8C4D40

Please update the address in the djy0.md file.

**Comment by jiangying000** [comment]
change starcoin chain account address: #43

**Pull request merged**
